apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/REPLACE_WITH_YOUR_ORG/k8s-tech-challenge-aws'
    targetRevision: HEAD
    path: charts/testapp
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
