replicaCount: 1
image:
  repository: pmotwani575/hello-test-app
  tag: 91a098e670490ae2b54c45471882c5b8e3888d9e
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  host: testapp.k8stestapp.element.in
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
