replicaCount: 1
image:
  repository: pmotwani575/hello-test-app
  tag: latest
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  host: testapp.example.com
  path: /
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
