replicaCount: 1
image:
  repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/testapp
  tag: latest
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  host: testapp.example.com
  path: /
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
