name: CI/CD — Build and update Helm chart

on:
  push:
    branches: [ "main" ]
    paths:
      - "app/**"
      - "Dockerfile"
      - "charts/testapp/**"

permissions:
  contents: write

jobs:
  build-and-update-helm:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: pmotwani575/hello-test-app
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Install yq
        run: |
          sudo curl -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update Helm chart values.yaml
        run: |
          echo "Updating chart with new image $IMAGE_REPO:$IMAGE_TAG"
          yq eval ".image.repository = \"${IMAGE_REPO}\"" -i charts/testapp/values.yaml
          yq eval ".image.tag = \"${IMAGE_TAG}\"" -i charts/testapp/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add charts/testapp/values.yaml
          if git diff --cached --quiet; then
            echo "No changes detected in values.yaml"
          else
            git commit -m "ci: update image to $IMAGE_TAG [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
